# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62c148029e66f2dcddcd6257508c1331ee6e091b79f7a126b9a1bf4a3d46839a821300a611e88143fc9cf03a1bf9ce651727762c6310e0b13c85e42d56f3de7

test:
  secret_key_base: f20d029ee77d677ea5be6dbcd50d93023dbdb22f7a3ad2108ba2bbe9318cbeec5bf3b1d33d98a538625beca4a9eb6f4866a244e4dd30942600071ecd2c9fa8e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
